# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20161125_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='C1', max_length=10),
        ),
    ]
